language: java
jdk: oraclejdk8
branches:
  only:
  - master
before_install: 
  - mkdir -p ~/.steam/steam/steamapps/workshop/content/281990
  - mkdir -p ~/.steam/steam/steamapps/common/Stellaris
  - mkdir -p ~/.local/share/Paradox\ Interactive/Stellaris/mod
script: mvn clean install
after_success:
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://idrinth.de/codacy-coverage-reporter-assembly-latest.jar
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r ./target/site/jacoco/jacoco.xml
